main:
  - name: Discrete Mathematics
    url: /discrete-mathematics/
  - name: Wiki For All
    url: /wiki-for-all/

global: 
  - name: "বাংলা লার্নিং মডিউল"
    url: "/learn-bengali/"
    params:
      label: অবাংলাভাষীদের জন্য বাংলা শিক্ষণ সামগ্রী
  - name: "পরিষদ বাংলা অভিধান"
    url: "/parisad-bengali-dictionary/"
    params:
      label: বাংলা ভাষার সর্বাধুনিক, সর্ববৃহৎ ও সমৃদ্ধ বাংলা অভিধান
  - name: "পরিষদ লোকজ শব্দকোষ"
    url: #
    params:
      label: ময়মনসিংহে অঞ্চলের আঞ্চলিক ভাষা অভিধান
  - name: "পরিষদ সমার্থক শব্দকোষ"
    url: #
    params:
      label: ময়মনসিংহে অঞ্চলের আঞ্চলিক ভাষা অভিধান
  - name: "বাংলা প্রবাদ সংগ্রহ"
    url: #
    params:
      label: ময়মনসিংহে অঞ্চলের আঞ্চলিক ভাষা অভিধান
  - name: "বাঙালির যা যা"
    url: #
    params:
      label: বাঙালির ভাষা, প্রযুক্তি, সংস্কৃতি সমস্ত কিছু নিয়ে গ্রন্থ
  - name: "Discrete Mathematics in Bengali"
    url: "/discrete-mathematics/"
    params:
      label: বাঙালির ভাষা, প্রযুক্তি, সংস্কৃতি সমস্ত কিছু নিয়ে গ্রন্থ
globallinks:
  - name: "ঐশিক আইটি সেন্টার"
    url: "https://itc.aishikrehman.com/"
    params:
      label: লক্ষীগঞ্জ বাজার, ঈশ্বরগঞ্জ, ময়মনসিংহ
  - name: "ঐশিক লার্নিং সেন্টার"
    url: "https://learn.aishikrehman.com/"
    params:
      label: লক্ষীগঞ্জ বাজার, ঈশ্বরগঞ্জ, ময়মনসিংহ
  - name: "বাংলা পরিষদ"
    url: "https://bengalicouncil.github.io/"

prabad-sangraha:
  - name: "বর্ণানুক্রমে"
    url: "#"
    weight: 1
    params: 
      hidefornow: true
  - name: "অ"
    url: "/অ/"
    parent: "বর্ণানুক্রমে"
  - name: "আ"
    url: "/আ/"
    parent: "বর্ণানুক্রমে"
  - name: "ই"
    url: "/ই/"
    parent: "বর্ণানুক্রমে"
  - name: "ঈ"
    url: "/ঈ/"
    parent: "বর্ণানুক্রমে"
  - name: "সূচিপত্র"
    url: "#"
    params: 
      hidefornow: true

wiki-for-all:
  - name: "How to Become a Wikipedian"
    url: "/become-a-wikipedian/"
    weight: 1
  - name: "Introduction to Wikipedia"
    url: "/introduction-to-wikipedia/"
    weight: 1
    parent: "How to Become a Wikipedian"
  - name: "Navigating Wikipedia"
    url: "/navigating-wikipedia/"
    weight: 2
    parent: "How to Become a Wikipedian"
  - name: "Editing Articles"
    url: "/editing-articles/"
    weight: 3
    parent: "How to Become a Wikipedian"
  - name: "Article Creation"
    url: "/article-creation/"
    weight: 4
    parent: "How to Become a Wikipedian"
  - name: "Advanced Editing"
    url: "/advanced-editing/"
    weight: 5
    parent: "How to Become a Wikipedian"
  - name: "Becoming an Admin"
    url: "/becoming-an-admin/"
    weight: 6
    parent: "How to Become a Wikipedian"
  - name: "Contributing to the Community"
    url: "/contributing-to-community/"
    weight: 7
    parent: "How to Become a Wikipedian"
  - name: "Advanced Technical Skills"
    url: "/advanced-technical-skills/"
    weight: 8
    parent: "How to Become a Wikipedian"
  - name: "Outreach and Wiki Projects"
    url: "/outreach-and-wiki-projects/"
    weight: 9
    parent: "How to Become a Wikipedian/"

  - name: "Getting Started"
    url: "/getting-started"
    weight: 2
  - name: "Creating Your Account"
    url: "/creating-your-account"
    weight: 1
    parent: "Getting Started"
  - name: "Your First Edit"
    url: "/your-first-edit"
    weight: 2

    parent: "Getting Started"
  - name: "Editing Basics"
    url: "/editing-basics"
    weight: 3
  - name: "Basic Editing Tools"
    url: "/basic-editing-tools"
    weight: 1
    parent: "Editing Basics"
  - name: "Formatting Text"
    url: "/formatting-text"
    weight: 2
    parent: "Editing Basics"
  - name: "Adding References"
    url: "/adding-references"
    weight: 3
    parent: "Editing Basics"
  - name: "Advanced Skills"
    url: "/advanced-skills"
    weight: 4
  - name: "Templates and Infoboxes"
    url: "/templates-and-infoboxes"
    weight: 1
    parent: "Advanced Skills"
  - name: "Bots and Automation"
    url: "/bots-and-automation"
    weight: 2
    parent: "Advanced Skills"
  - name: "Using Pywikibot"
    url: "/using-pywikibot"
    weight: 3
    parent: "Advanced Skills"
  - name: "Wikipedia Policies"
    url: "/wikipedia-policies"
    weight: 5
    parent: null
  - name: "Neutral Point of View"
    url: "/neutral-point-of-view"
    weight: 1
    parent: "Wikipedia Policies"
  - name: "Verifiability"
    url: "/verifiability"
    weight: 2
    parent: "Wikipedia Policies"
  - name: "Copyright Policies"
    url: "/copyright-policies"
    weight: 3
    parent: "Wikipedia Policies"
  - name: "Becoming an Administrator"
    url: "/becoming-an-administrator"
    weight: 6
  - name: "What Admins Do"
    url: "/what-admins-do"
    weight: 1
    parent: "Becoming an Administrator"
  - name: "Admin Tools and Permissions"
    url: "/admin-tools-and-permissions"
    weight: 2
    parent: "Becoming an Administrator"
  - name: "Admin Nomination Process"
    url: "/admin-nomination-process"
    weight: 3
    parent: "Becoming an Administrator"
  - name: "Community and Outreach"
    url: "/community-and-outreach"
    weight: 7
  - name: "Joining WikiProjects"
    url: "/joining-wikiprojects"
    weight: 1
    parent: "Community and Outreach"
  - name: "Organizing Meetups"
    url: "/organizing-meetups"
    weight: 2
    parent: "Community and Outreach"
  - name: "Dispute Resolution"
    url: "/dispute-resolution"
    weight: 3
    parent: "Community and Outreach"
  - name: "WikiTools and Resources"
    url: "/wiki-tools-and-resources"
    weight: 8
  - name: "Wikidata Basics"
    url: "/wikidata-basics"
    weight: 1
    parent: "WikiTools and Resources"
  - name: "Wikimedia Commons"
    url: "/wikimedia-commons"
    weight: 2
    parent: "WikiTools and Resources"
  - name: "Pageviews and Stats"
    url: "/pageviews-and-stats"
    weight: 3
    parent: "WikiTools and Resources"

discrete-mathematics:
  - weight: 1
    identifier: unit__zero
    name: "Preface"
    url: /preface/
  - weight: 11
    name: About the Author
    url: /about-the-author/
    parent: unit__zero
  - weight: 12
    name:   How to Use This Book
    url: /how-to-use-this-book/
    parent: unit__zero

  - weight: 20
    identifier: unit__basic
    name: "Discrete Mathematics"
    url: /
  - name: What and Why is Discerete Mathematics
    url: #
    parent: unit__basic
  - name:  Goals of a Discrete Mathematics Course
    url: #
    parent: unit__basic

  - weight: 1
    identifier: unit__one
    name: "The Foundations: Logic and Proofs"
    url: /the-foundations-logic-and-proofs/
  - weight: 2
    parent: unit__one
    name: "Propositional Logic"
    url: /propositional-logic/
  - weight: 3
    parent: unit__one
    name: "Applications of Propositional Logic"
    url: /applications-of-propositional-logic/
  - weight: 4
    parent: unit__one
    name: "Propositional Equivalences"
    url: /propositional-equivalences/
  - weight: 5
    parent: unit__one
    name: "Predicates and Quantifiers"
    url: /predicates-and-quantifiers/
  - weight: 6
    parent: unit__one
    name: "Nested Quantifiers"
    url: /nested-quantifiers/
  - weight: 7
    parent: unit__one
    name: "Rules of Inference"
    url: /rules-of-inference/
  - weight: 8
    parent: unit__one
    name: "Introduction to Proofs"
    url: /introduction-to-proofs/
  - weight: 9
    parent: unit__one
    name: "Proof Methods and Strategy"
    url: /proof-methods-and-strategy/
  - weight: 10
    parent: unit__one
    name: "End-of-Chapter Material"
    url: /end-of-chapter-material/
  - weight: 11
    identifier: unit__two
    name: "Basic Structures: Sets, Functions, Sequences, Sums, and Matrices"
    url: /basic-structures-sets-functions-sequences-sums-and-matrices/
  - weight: 12
    parent: unit__two
    name: "Sets"
    url: /sets/
  - weight: 13
    parent: unit__two
    name: "Set Operations"
    url: /set-operations/
  - weight: 14
    parent: unit__two
    name: "Functions"
    url: /functions/
  - weight: 15
    parent: unit__two
    name: "Sequences and Summations"
    url: /sequences-and-summations/
  - weight: 16
    parent: unit__two
    name: "Cardinality of Sets"
    url: /cardinality-of-sets/
  - weight: 17
    parent: unit__two
    name: "Matrices"
    url: /matrices/
  - weight: 18
    parent: unit__two
    name: "End-of-Chapter Material"
    url: /end-of-chapter-material/
  - weight: 19
    identifier: unit__three
    name: "Algorithms"
    url: /algorithms/
  - weight: 20
    parent: unit__three
    name: "Algorithms"
    url: /algorithms/
  - weight: 21
    parent: unit__three
    name: "The Growth of Functions"
    url: /the-growth-of-functions/
  - weight: 22
    parent: unit__three
    name: "Complexity of Algorithms"
    url: /complexity-of-algorithms/
  - weight: 23
    parent: unit__three
    name: "End-of-Chapter Material"
    url: /end-of-chapter-material/
  - weight: 24
    identifier: unit__four
    name: "Number Theory and Cryptography"
    url: /number-theory-and-cryptography/
  - weight: 25
    parent: unit__four
    name: "Divisibility and Modular Arithmetic"
    url: /divisibility-and-modular-arithmetic/
  - weight: 26
    parent: unit__four
    name: "Integer Representations and Algorithms"
    url: /integer-representations-and-algorithms/
  - weight: 27
    parent: unit__four
    name: "Primes and Greatest Common Divisors"
    url: /primes-and-greatest-common-divisors/
  - weight: 28
    parent: unit__four
    name: "Solving Congruences"
    url: /solving-congruences/
  - weight: 29
    parent: unit__four
    name: "Applications of Congruences"
    url: /applications-of-congruences/
  - weight: 30
    parent: unit__four
    name: "Cryptography"
    url: /cryptography/
  - weight: 31
    parent: unit__four
    name: "End-of-Chapter Material"
    url: /end-of-chapter-material/
  - weight: 32
    identifier: unit__five
    name: "Induction and Recursion"
    url: /induction-and-recursion/
  - weight: 33
    parent: unit__five
    name: "Mathematical Induction"
    url: /mathematical-induction/
  - weight: 34
    parent: unit__five
    name: "Strong Induction and Well-Ordering"
    url: /strong-induction-and-well-ordering/
  - weight: 35
    parent: unit__five
    name: "Recursive Definitions and Structural Induction"
    url: /recursive-definitions-and-structural-induction/
  - weight: 36
    parent: unit__five
    name: "Recursive Algorithms"
    url: /recursive-algorithms/
  - weight: 37
    parent: unit__five
    name: "Program Correctness"
    url: /program-correctness/
  - weight: 38
    parent: unit__five
    name: "End-of-Chapter Material"
    url: /end-of-chapter-material/
  - weight: 39
    identifier: unit__six
    name: "Counting"
    url: /counting/
  - weight: 40
    parent: unit__six
    name: "The Basics of Counting"
    url: /the-basics-of-counting/
  - weight: 41
    parent: unit__six
    name: "The Pigeonhole Principle"
    url: /the-pigeonhole-principle/
  - weight: 42
    parent: unit__six
    name: "Permutations and Combinations"
    url: /permutations-and-combinations/
  - weight: 43
    parent: unit__six
    name: "Binomial Coefficients and Identities"
    url: /binomial-coefficients-and-identities/
  - weight: 44
    parent: unit__six
    name: "Generalized Permutations and Combinations"
    url: /generalized-permutations-and-combinations/
  - weight: 45
    parent: unit__six
    name: "Generating Permutations and Combinations"
    url: /generating-permutations-and-combinations/
  - weight: 46
    parent: unit__six
    name: "End-of-Chapter Material"
    url: /end-of-chapter-material/
  - weight: 47
    identifier: unit__seven
    name: "Discrete Probability"
    url: /discrete-probability/
  - weight: 48
    parent: unit__seven
    name: "An Introduction to Discrete Probability"
    url: /an-introduction-to-discrete-probability/
  - weight: 49
    parent: unit__seven
    name: "Probability Theory"
    url: /probability-theory/
  - weight: 50
    parent: unit__seven
    name: "Bayes' Theorem"
    url: /bayes-theorem/
  - weight: 51
    parent: unit__seven
    name: "Expected Value and Variance"
    url: /expected-value-and-variance/
  - weight: 52
    parent: unit__seven
    name: "End-of-Chapter Material"
    url: /end-of-chapter-material/
  - weight: 53
    identifier: unit__eight
    name: "Advanced Counting Techniques"
    url: /advanced-counting-techniques/
  - weight: 54
    parent: unit__eight
    name: "Applications of Recurrence Relations"
    url: /applications-of-recurrence-relations/
  - weight: 55
    parent: unit__eight
    name: "Solving Linear Recurrence Relations"
    url: /solving-linear-recurrence-relations/
  - weight: 56
    parent: unit__eight
    name: "Divide-and-Conquer Algorithms and Recurrence Relations"
    url: /divide-and-conquer-algorithms-and-recurrence-relations/
  - weight: 57
    parent: unit__eight
    name: "Generating Functions"
    url: /generating-functions/
  - weight: 58
    parent: unit__eight
    name: "Inclusion-Exclusion"
    url: /inclusion-exclusion/
  - weight: 59
    parent: unit__eight
    name: "Applications of Inclusion-Exclusion"
    url: /applications-of-inclusion-exclusion/
  - weight: 60
    parent: unit__eight
    name: "End-of-Chapter Material"
    url: /end-of-chapter-material/
  - weight: 61
    identifier: unit__nine
    name: "Relations"
    url: /relations/
  - weight: 62
    parent: unit__nine
    name: "Relations and Their Properties"
    url: /relations-and-their-properties/
  - weight: 63
    parent: unit__nine
    name: "n-ary Relations and Their Applications"
    url: /n-ary-relations-and-their-applications/
  - weight: 64
    parent: unit__nine
    name: "Representing Relations"
    url: /representing-relations/
  - weight: 65
    parent: unit__nine
    name: "Closures of Relations"
    url: /closures-of-relations/
  - weight: 66
    parent: unit__nine
    name: "Equivalence Relations"
    url: /equivalence-relations/
  - weight: 67
    parent: unit__nine
    name: "Partial Orderings"
    url: /partial-orderings/
  - weight: 68
    parent: unit__nine
    name: "End-of-Chapter Material"
    url: /end-of-chapter-material/
  - weight: 69
    identifier: unit__ten
    name: "Graphs"
    url: /graphs/
  - weight: 70
    parent: unit__ten
    name: "Graphs and Graph Models"
    url: /graphs-and-graph-models/
  - weight: 71
    parent: unit__ten
    name: "Graph Terminology and Special Types of Graphs"
    url: /graph-terminology-and-special-types-of-graphs/
  - weight: 72
    parent: unit__ten
    name: "Representing Graphs and Graph Isomorphism"
    url: /representing-graphs-and-graph-isomorphism/
  - weight: 73
    parent: unit__ten
    name: "Connectivity"
    url: /connectivity/
  - weight: 74
    parent: unit__ten
    name: "Euler and Hamilton Paths"
    url: /euler-and-hamilton-paths/
  - weight: 75
    parent: unit__ten
    name: "Shortest-Path Problems"
    url: /shortest-path-problems/
  - weight: 76
    parent: unit__ten
    name: "Planar Graphs"
    url: /planar-graphs/
  - weight: 77
    parent: unit__ten
    name: "Graph Coloring"
    url: /graph-coloring/
  - weight: 78
    parent: unit__ten
    name: "End-of-Chapter Material"
    url: /end-of-chapter-material/
  - weight: 79
    identifier: unit__eleven
    name: "Trees"
    url: /trees/
  - weight: 80
    parent: unit__eleven
    name: "Introduction to Trees"
    url: /introduction-to-trees/
  - weight: 81
    parent: unit__eleven
    name: "Tree Traversal"
    url: /tree-traversal/
  - weight: 82
    parent: unit__eleven
    name: "Binary Trees"
    url: /binary-trees/
  - weight: 83
    parent: unit__eleven
    name: "Tree Algorithms"
    url: /tree-algorithms/
  - weight: 84
    parent: unit__eleven
    name: "Spanning Trees"
    url: /spanning-trees/
  - weight: 85
    parent: unit__eleven
    name: "End-of-Chapter Material"
    url: /end-of-chapter-material/
  - weight: 86
    identifier: unit__twelve
    name: "Boolean Algebra"
    url: /boolean-algebra/
  - weight: 87
    parent: unit__twelve
    name: "Boolean Functions"
    url: /boolean-functions/
  - weight: 88
    parent: unit__twelve
    name: "Logic Gates and Circuits"
    url: /logic-gates-and-circuits/
  - weight: 89
    parent: unit__twelve
    name: "Simplification of Boolean Expressions"
    url: /simplification-of-boolean-expressions/
  - weight: 90
    parent: unit__twelve
    name: "Boolean Algebra and Digital Logic"
    url: /boolean-algebra-and-digital-logic/
  - weight: 91
    parent: unit__twelve
    name: "End-of-Chapter Material"
    url: /end-of-chapter-material/