# Language Data
languageCode: bn-BD # The language code for the site
languageDirection: ltr # Text direction: left-to-right
languageName: বাংলা # Display name of the language
defaultLang: bn # Should match DefaultContentLanguage; used for checks (not necessary for monolingual sites)

# Site
subtitle: অভিধানকার | বিসিএসই # Subtitle of the site; 
subdomain: "" # Subdomain for the site; leave empty if not applicable
livepath: "/" # Path for the site; leave empty if not applicable

# Accesibilty and Features
defaultColorMode: "light" # Changing this requires some changes to the colormode.js script; otherwise, it won't work
activateColorModeToogler: true # Activates the dark/light color mode toggler
activateGlobalMenu: true # Activates the Global Menu if required
siteWideDynamicTitle: false
useSubNavBar: true

# Packeges/Dependencies 
usejQuery: false # Enables jQuery if needed
useMathJax: true
useBootstrapMod: true # Uses a modified version of Bootstrap 5.3.3; set to false to use the Bootstrap CDN version
useBootstrapIcons: true # Enables Bootstrap Icons; recommended setting is "true"
useBootstrapBundleJS: true # Enables Bootstrap Bundle JS
BootstrapCDNVersion: "5.3.3" # Applies only if useBootstrapMod is set to false


# Authors Information
author:
  name: Aishik Rehman
  jobtitle: Wikimedian and Lexicolgist and CSEr.
  url: "https://aishikrehman.com/about/"
  email: hello@aishikrehman.com
  locality: Mymensingh, Bangladesh
  social:
    facebook: "https://facebook.com/aishikrehman"
    linkedin: "https://linkedin.com/in/aishikrehman"
    # youtube: "https://youtube.com/@aishikrehman"
    github: "https://github.com/aishikrehman"
    wikipedia: "https://bn.wikipedia.com/wiki/User:Aishik Rehman"
    #twitter: RehmanAishik
  phone: "+880 1601660666"
  picture: /assets/images/Aishik Rehman_Mymensingh_2019.jpg

# GitHub Repository Information
github:
  user: aishikrehman # GitHub username
  repo: aishikrehman.github.io # Repository name
  branch: main # Default branch

schema:
  name: Aishik Rehman # Schema name for SEO
  alternateName: "Oishik Rehman" # Alternate name for SEO
  image: /assets/images/Aishik Rehman-og-image.png # Path to the OG image
  google_site_verification: "0J8IfuFx-q_dRuc9I1q0tcVBKAMOTAN3gr27m5OwKzQ" # Google site verification token
  fb_app_id: "" # Facebook Application ID (leave empty if not applicable)